# -*- mode: ruby -*-
# vi: set ft=ruby :

# Make sure the following boxes are installed:
# PROVIDER: virtualbox
# vagrant box add precise64-20131014 https://cloud-images.ubuntu.com/vagrant/precise/20131014/precise-server-cloudimg-amd64-vagrant-disk1.box

Vagrant.configure("2") do |config|
  config.vm.define "epicloops" do |epicloops|
    epicloops.vm.box = "precise64-20131014"
    epicloops.vm.hostname = "epicloops"
    epicloops.vm.network "forwarded_port", guest: 8000, host: 8000

    epicloops.vm.synced_folder   ".",                             "/home/vagrant/epicloops.com",         disabled: false
    epicloops.vm.synced_folder   "vagrant/synced-folders/salt/",  "/srv/salt/base",                disabled: false
    epicloops.vm.synced_folder   "~/dotfiles-protected/",         "/srv/salt/dotfiles-protected",  disabled: false

    # Install salt, generate keys, update minion config, run state.highstate
    epicloops.vm.provision "shell", path: "vagrant/bootstrap.sh"
  end
end
